import type { Metadata } from "next";
import "./globals.css";
import {poppinsFont, interFont} from "./fonts";
// import { ThemeProvider } from "../context/ThemeContext";
import Navbar from "@/components/Navbar";
import ProviderWrapper from "@/store/Provider";
import ThemeHydrate from "@/store/ThemeHydrate";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppinsFont.variable} ${interFont.variable} overflow-x-hidden antialiased bg-backgroundColor dark:bg-backgroundDarkColor transition-all duration-500`}>
        {/* <ThemeProvider> */}
          <ProviderWrapper>
            <ThemeHydrate>
            <Navbar />
            {children}
            <Footer />
            </ThemeHydrate>
          </ProviderWrapper>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
